### ISSUE TITLE
Is this service limited by Gmail limit of 100 emails per day?

### ISSUE THREAD

**Issue by cupelapps** [sharptag/zender-csharp#10]
Is this service limited by Gmail limit of 100 emails per day?

**Comment by jhallal** [comment]
No it is not limited, are you facing any issue?

**Comment by cupelapps** [comment]
Hi,
First thank you for your service. I have no issues in using the library. I want to make sure that this service will be free forever or any plans to introduce premium plans in future. I want to use your service for my clients and also for me sending newsletters and transaction emails. 
1. Whether Zender API supports sending emails in bulk (newsletters)?  If so what are the limitations. Or Can i schedule the emails one by one to send to bunch of clients?
2. What about the privacy policy of the to emails used

**Comment by jhallal** [comment]
@cupelapps
1-You can send the same email/newsletter to bulk to contacts (by adding them to the receiver list) or you can send the email to each contact separately, it is your choice. You can use our site to build your newsletter and schedule it for sending, or you can develop your own scheduling tool and integrate it with our API.
2-We guaranty the privacy of your contacts and emails. Please refer to our [privacy policy](http://zender.sharptag.com/Privacy) section on the website

**Comment by cupelapps** [comment]
Hi
Thank you for clarifying. But i am getting this error message on received email
"Check if your Gmail message is authenticated".

**Comment by jhallal** [comment]
@cupelapps 
Please share the code you are using to send the email, but without the API Key. Your API Key should not be shared with anyone.

**Comment by cupelapps** [comment]
Hi
This is the code i am using
 
ZenderMessage message = new ZenderMessage("");
            MailAddress from = new MailAddress("smssprofessor@zoho.com");
            MailAddress to1 = new MailAddress("smssprofessor@gmail.com");
            MailAddress to2 = new MailAddress("cupelmd@gmail.com");          
            message.From = from;
            message.To.Add(to1);
            message.To.Add(to2);
            message.Subject = "Thank you for subscribing";
            message.Body = "We thank you for your subscription to our store. We will send special offers and promotions.";
            message.IsBodyHtml = true;
            message.SendMailAsync();

**Comment by cupelapps** [comment]
Thank you Jhallal,
I have checked with Inbox by google. And warning message is gone. But with older gmail UI, the warning shows. in yahoo there is no warning message. :)
**Regards**
Muthu

**Comment by jhallal** [comment]
@cupelapps you are welcome. if you have any additional question don't hesitate to ask, I will be glad to support

**Comment by cupelapps** [comment]
Hi
Thank you for your support
