### ISSUE TITLE
Email Not Sending

### ISSUE THREAD

**Issue by surepallysaritha** [sharptag/zender-csharp#9]
Hi,
 
As per the given instructions from Zender. I have gone through your code and implemented the same. 
but the email not sending. not getting any error also.
Please let me know what is the solution asap.

this is my code to send an email.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Net.Mail;
using Zender.Mail;
public partial class _Default : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            ZenderMessage message = new ZenderMessage("09f12588-3d81-47b8-a1ab-535091b20049");

            MailAddress from = new MailAddress("surepallysaritha@gmail.com");

            MailAddress to = new MailAddress("saritha.dussa84@gmail.com");

            message.From = from;

            message.To.Add(to);

            message.Subject = "Welcome";

            message.Body = "Hi";

            message.IsBodyHtml = true;

            message.SendMailAsync();
        }
    }
}

Thanks.
S.Saritha

**Comment by jhallal** [comment]
Hi Saritha, after checking the reported issue. I found out that your Zender API Key was registered with "dsaritha@varrah.in" and not "surepallysaritha@gmail.com". so to fix the issue you need to use "dsaritha@varrah.in" as the sender email address. your code should be modified as per the following:
.....
MailAddress from = new MailAddress("dsaritha@varrah.in");
....
